### ISSUE TITLE
No search option, as in previous Flatcar docs had

### ISSUE THREAD

**Issue by rata** [kinvolk/docs#8]
**Current situation**
There is no search option in the documentation website.

**Impact**
I can't find information on the documentation, or it takes too much time

**Ideal future situation**
Restore a search function, as the previous flatcar website had.

**Comment by joaquimrocha** [comment]
Since the new docs renderer is a different system, it's not about restoring the search funciton but about implementing one. I will close this as this functionality belongs to the Kinvolk website.

**Comment by rata** [comment]
The new issue is: https://github.com/kinvolk/website/issues/243
